const lessons=[
{title:'Greetings',he:'שלום, מה שלומך?',en:'Hello, how are you?',say:'Shalom, ma shlom-kha?',words:[['שלום','hello / peace'],['מה','what'],['שלומך','your well-being']],insight:'The כ at the end of שלומך is a soft kh sound, made at the back of the throat.',grammar:'Hebrew often asks “what is your well-being?” instead of using the English form.',biblical:'Shalom means peace, wholeness, and well-being—not merely the absence of conflict.'},
{title:'Responding',he:'אני טוב, תודה.',en:'I am well, thank you.',say:'Ani tov, toda.',words:[['אני','I'],['טוב','good / well'],['תודה','thank you']],insight:'אני (ani) is the first-person pronoun “I.”',grammar:'Adjectives often follow the noun or pronoun they describe.',biblical:'Gratitude is a frequent response in the Psalms.'},
{title:'Please and thank you',he:'בבקשה, תודה רבה.',en:'Please, thank you very much.',say:'Bevakasha, toda raba.',words:[['בבקשה','please / you’re welcome'],['תודה','thank you'],['רבה','much / many']],insight:'בבקשה can mean “please” or “you’re welcome,” depending on context.',grammar:'רבה is the feminine form of “much,” matching תודה, a feminine noun.',biblical:'Words of gratitude help turn attention toward God and neighbor.'},
{title:'Introducing yourself',he:'קוראים לי דניאל.',en:'My name is Daniel.',say:'Kor-im li Dani-el.',words:[['קוראים','they call'],['לי','to me / my'],['שם','name']],insight:'Hebrew introduces a name with a phrase that literally means “they call me.”',grammar:'לי combines ל (to) with י (me).',biblical:'Names in the Bible often carry meaning and family history.'},
{title:'Where are you from?',he:'מאיפה אתה?',en:'Where are you from? (to a man)',say:'Me-eifo ata?',words:[['מאיפה','from where'],['אתה','you (masculine)'],['את','you (feminine)']],insight:'Hebrew has masculine and feminine forms for “you.”',grammar:'Questions can be formed by using a question word without changing word order.',biblical:'The Bible often describes people by their home and journey.'},
{title:'At a café',he:'אני רוצה מים, בבקשה.',en:'I would like water, please.',say:'Ani rotze mayim, bevakasha.',words:[['רוצה','want (masculine speaker)'],['מים','water'],['בבקשה','please']],insight:'מים (mayim) is the everyday word for water.',grammar:'רוצה changes form with the speaker; this form is masculine singular.',biblical:'Water is an important image of life, welcome, and renewal in Scripture.'},
{title:'Finding a place',he:'איפה התחנה?',en:'Where is the station?',say:'Eifo ha-takhana?',words:[['איפה','where'],['התחנה','the station'],['ה','the']],insight:'The definite article ה attaches as a prefix to a noun.',grammar:'Hebrew uses no separate word for “the.”',biblical:'Asking for directions is a practical way to meet a place and its people.'},
{title:'A kind wish',he:'יום טוב!',en:'Have a good day!',say:'Yom tov!',words:[['יום','day'],['טוב','good'],['שלום','peace']],insight:'יום טוב (yom tov) literally means “good day.”',grammar:'In this phrase, טוב follows יום.',biblical:'The Hebrew Bible uses “good” to describe creation and God’s gifts.'}
];
const $=s=>document.querySelector(s);let state=JSON.parse(localStorage.getItem('daber-progress')||'{}');let idx=state.idx||0,mode='lesson',skill='learn',earned=new Set(state.earned||[]),scores=state.scores||{pronounce:0,translate:0,read:0};const save=()=>localStorage.setItem('daber-progress',JSON.stringify({idx,earned:[...earned],scores,last:state.last||new Date().toDateString(),streak:state.streak||1}));
function render(){const l=lessons[idx];$('#category').textContent=`BEGINNER · ${l.title.toUpperCase()}`;$('#lessonTitle').textContent=`Lesson ${idx+1} of ${lessons.length}`;$('#hebrew').textContent=l.he;$('#english').textContent=l.en;$('#translit').textContent=l.say;$('#insight').textContent=l.insight;$('#grammar').textContent=l.grammar;$('#biblical').textContent=l.biblical;$('#streak').textContent=state.streak||1;$('#mastery').textContent=`Beginner · ${earned.size} of ${lessons.length} lessons mastered`;for(const k of ['pronounce','translate','read']){const p=Math.round((scores[k]||0)/lessons.length*100);const prefix=k==='pronounce'?'pron':k==='translate'?'trans':'read';$('#'+prefix+'Pct').textContent=p+'%';$('#'+prefix+'Progress').value=p}$('#detail').innerHTML=skill==='learn'?l.words.map(w=>`<span class="word" style="display:inline-block;margin:3px"><b lang="he" dir="rtl">${w[0]}</b> — ${w[1]}</span>`).join(''):skill==='pronounce'?`<p>Listen, then say: <strong>${l.say}</strong></p><p>Break it into short sound groups and repeat at a comfortable pace.</p>`:skill==='translate'?`<p>Translate this sentence: <strong lang="he" dir="rtl">${l.he}</strong></p><label>Your translation <input id="answer" autocomplete="off"></label>`:`<p>Read aloud: <strong lang="he" dir="rtl">${l.he}</strong></p><p>Notice the letters and vowel sounds, then reveal the meaning.</p>`;$('#hint').textContent=skill==='translate'?'TRANSLATE TO ENGLISH':skill==='read'?'READ THE HEBREW':skill==='pronounce'?'LISTEN AND REPEAT':'UNDERSTAND THE WHOLE SENTENCE';$('#action').textContent=skill==='translate'?'Check translation →':skill==='read'?'Reveal meaning →':skill==='pronounce'?'Mark pronunciation practiced →':'I understand →';$('#english').hidden=skill==='read';$('#words').innerHTML=lessons.flatMap(x=>x.words).map(w=>`<div class="word"><b lang="he" dir="rtl">${w[0]}</b>${w[1]}</div>`).join('')}
$('#action').onclick=()=>{const l=lessons[idx];if(skill==='translate'){const a=$('#answer').value.trim().toLowerCase();if(!a){$('#feedback').textContent='Type a translation first.';return}if(a.includes('hello')||a.includes('how are you')||a.includes('peace')||a.includes(l.en.split(' ')[0].toLowerCase())){scores.translate=(scores.translate||0)+1;$('#feedback').textContent='Good work. '+l.en}else{$('#feedback').textContent='Try again, or study the whole-sentence meaning above.';return}}else if(skill==='read'){scores.read=(scores.read||0)+1;$('#feedback').textContent=l.en+' · '+l.say}else if(skill==='pronounce'){scores.pronounce=(scores.pronounce||0)+1;$('#feedback').textContent='Practice saved. Listen once more, then continue.'}else{earned.add(idx);$('#feedback').textContent='Lesson marked complete.'}idx=(idx+1)%lessons.length;save();setTimeout(()=>{ $('#feedback').textContent='';render()},850)};
$('#audio').onclick=()=>{if(!('speechSynthesis'in window)){ $('#feedback').textContent='Hebrew audio is not available on this device.';return}const u=new SpeechSynthesisUtterance(lessons[idx].he);u.lang='he-IL';speechSynthesis.speak(u)};
document.querySelectorAll('[data-skill]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-skill]').forEach(x=>x.classList.remove('active'));b.classList.add('active');skill=b.dataset.skill;$('#feedback').textContent='';render()});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-mode]').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.mode;if(mode==='review'){idx=lessons.findIndex((_,i)=>!earned.has(i));if(idx<0)idx=0}else if(mode==='foundations'){skill='read';document.querySelector('[data-skill="read"]').click()}else if(mode==='level'){idx=0;skill='translate';document.querySelector('[data-skill="translate"]').click()}else if(mode==='conversation'){idx=3;skill='pronounce';document.querySelector('[data-skill="pronounce"]').click()}else{skill='learn';document.querySelector('[data-skill="learn"]').click()}render()});$('#reset').onclick=()=>{if(confirm('Reset all Daber progress saved in this browser?')){localStorage.removeItem('daber-progress');state={};idx=0;earned.clear();scores={pronounce:0,translate:0,read:0};render()}};render();
